CREATE TABLE IF NOT EXISTS sports_videos (
    id SERIAL PRIMARY KEY,
    video_link TEXT,
    title TEXT,
    description TEXT
);



INSERT INTO sports_videos (video_link, title, description) VALUES
('https://www.youtube.com/watch?v=abcd1234', 'Epic Soccer Goals Compilation', 'A collection of the best goals scored in football history.'),
('https://www.youtube.com/watch?v=efgh5678', 'NBA Top 10 Dunks of All Time', 'A countdown of the most jaw-dropping dunks in NBA history.'),
('https://www.youtube.com/watch?v=ijkl9012', 'Fastest 100m Sprints Ever Recorded', 'A look at the fastest sprinters and their record-breaking runs.'),
('https://www.youtube.com/watch?v=mnop3456', 'Greatest Tennis Rallies', 'Some of the longest and most exciting tennis rallies ever played.'),
('https://www.youtube.com/watch?v=qrst7890', 'Best Cricket Moments in History', 'Iconic moments from the world of cricket that fans will never forget.'),
('https://www.youtube.com/watch?v=uvwx5678', 'Top 10 UFC Knockouts', 'The most brutal and unexpected knockouts in UFC history.'),
('https://www.youtube.com/watch?v=yzab9012', 'Amazing Basketball Buzzer Beaters', 'Game-winning shots that left the crowd in awe.'),
('https://www.youtube.com/watch?v=cdef3456', 'Greatest Olympic Moments', 'A look back at some of the most memorable moments in Olympic history.'),
('https://www.youtube.com/watch?v=ghij7890', 'Legendary Formula 1 Overtakes', 'Some of the best overtakes ever seen in Formula 1 racing.'),
('https://www.youtube.com/watch?v=klmn5678', 'Insane Skateboarding Tricks', 'A compilation of the most daring and skillful skateboarding tricks.'),
('https://www.youtube.com/watch?v=mnop6789', 'Top 10 Rugby Tries', 'Incredible tries that showcase skill, speed, and teamwork.'),
('https://www.youtube.com/watch?v=qrst1234', 'Best Baseball Home Runs', 'The most unforgettable home runs in MLB history.'),
('https://www.youtube.com/watch?v=uvwx9012', 'Famous Boxing Knockouts', 'A collection of the most famous knockouts in boxing.'),
('https://www.youtube.com/watch?v=yzab3456', 'Extreme Snowboarding Stunts', 'High-adrenaline snowboarding tricks in extreme conditions.'),
('https://www.youtube.com/watch?v=cdef7890', 'Top 10 MMA Submissions', 'Incredible submissions that left fighters no choice but to tap out.'),
('https://www.youtube.com/watch?v=ghij5678', 'Greatest Cycling Finishes', 'The most exciting finishes in cycling history.'),
('https://www.youtube.com/watch?v=klmn9012', 'Top 10 Ice Hockey Goals', 'Spectacular goals from some of the greatest ice hockey players.'),
('https://www.youtube.com/watch?v=abcd5678', 'Motocross Freestyle Tricks', 'Daring and gravity-defying motocross stunts.'),
('https://www.youtube.com/watch?v=efgh9012', 'Best Volleyball Spikes', 'Powerful and unstoppable spikes from top volleyball players.'),
('https://www.youtube.com/watch?v=ijkl3456', 'Famous Golf Hole-in-Ones', 'Some of the most impressive hole-in-ones in golf history.'),
('https://www.youtube.com/watch?v=mnop7890', 'Top 10 Free Kicks in Football', 'Incredible free kicks that stunned goalkeepers and fans.'),
('https://www.youtube.com/watch?v=qrst5678', 'Fastest Pit Stops in Formula 1', 'Unbelievably fast pit stops that changed race outcomes.'),
('https://www.youtube.com/watch?v=uvwx1234', 'Greatest Long-Distance Running Finishes', 'Epic finishes in marathon and long-distance races.'),
('https://www.youtube.com/watch?v=yzab6789', 'Freestyle BMX Tricks', 'Some of the best BMX tricks ever performed.'),
('https://www.youtube.com/watch?v=cdef9012', 'Best Gymnastics Floor Routines', 'Graceful and powerful gymnastics floor routines.'),
('https://www.youtube.com/watch?v=ghij3456', 'Amazing Rock Climbing Feats', 'Incredible climbs that pushed human limits.'),
('https://www.youtube.com/watch?v=klmn7890', 'Greatest Wrestling Moves', 'Some of the most iconic moves in wrestling history.'),
('https://www.youtube.com/watch?v=abcd9012', 'Top 10 Extreme Sports Moments', 'A showcase of extreme sports at their finest.'),
('https://www.youtube.com/watch?v=efgh3456', 'Best Sports Comebacks Ever', 'Unbelievable comebacks that left fans speechless.'),
('https://www.youtube.com/watch?v=ijkl5678', 'Greatest Sports Rivalries', 'A deep dive into the most intense sports rivalries.'),
('https://www.youtube.com/watch?v=mnop9012', 'Top 10 Horse Racing Finishes', 'Exciting finishes in the history of horse racing.'),
('https://www.youtube.com/watch?v=qrst7890', 'Best Ice Skating Performances', 'Beautiful and breathtaking ice skating performances.'),
('https://www.youtube.com/watch?v=uvwx3456', 'Greatest Weightlifting Feats', 'A look at some of the strongest lifts in history.'),
('https://www.youtube.com/watch?v=yzab5678', 'Insane Parkour Stunts', 'Gravity-defying parkour moves from the best athletes.'),
('https://www.youtube.com/watch?v=cdef1234', 'Top 10 NFL Touchdowns', 'Incredible touchdown plays from NFL history.'),
('https://www.youtube.com/watch?v=ghij7890', 'Best Badminton Smashes', 'Lightning-fast smashes from top badminton players.'),
('https://www.youtube.com/watch?v=klmn5678', 'Greatest Water Polo Goals', 'Some of the best goals scored in water polo history.'),
('https://www.youtube.com/watch?v=abcd3456', 'Amazing Archery Shots', 'Incredible precision and skill in archery.'),
('https://www.youtube.com/watch?v=efgh7890', 'Top 10 Field Hockey Goals', 'Brilliant goals from world-class field hockey players.'),
('https://www.youtube.com/watch?v=ijkl9012', 'Best Fencing Moments', 'Spectacular fencing duels showcasing precision and skill.'),
('https://www.youtube.com/watch?v=mnop1234', 'Greatest Table Tennis Rallies', 'Fast-paced and thrilling table tennis rallies.'),
('https://www.youtube.com/watch?v=qrst9012', 'Most Unbelievable Curling Shots', 'Skillful and strategic curling shots in major tournaments.'),
('https://www.youtube.com/watch?v=uvwx5678', 'Top 10 Freestyle Skiing Tricks', 'Amazing aerial tricks in freestyle skiing.'),
('https://www.youtube.com/watch?v=yzab1234', 'Best Canoe Slalom Runs', 'Incredible skill in navigating rough waters.'),
('https://www.youtube.com/watch?v=cdef7890', 'Greatest Triathlon Finishes', 'Amazing endurance and speed in triathlon finishes.');
