CREATE TABLE IF NOT EXISTS sports_videos (
    id SERIAL PRIMARY KEY,
    video_link TEXT,
    title TEXT,
    description TEXT
);



INSERT INTO sports_videos (video_link, title, description) VALUES
('abcd1234efgh', 'Epic Soccer Goals Compilation 2025', 'A collection of the most thrilling goals scored in football matches from the 2025 season, featuring stars like Lionel Messi and Kylian Mbappé.'),
('bcde5678ijkl', 'NBA Finals 2025 Game 7 Highlights', 'Relive the intense moments of Game 7 as the Oklahoma City Thunder clinch the NBA title in a historic comeback.'),
('efgh9012mnop', 'Carlos Alcaraz’s French Open Victory 2025', 'Watch Carlos Alcaraz defend his French Open title in an epic 5-hour match against Jannik Sinner.'),
('ijkl3456qrst', 'Women’s PGA Championship 2025 Recap', 'Highlights of Minjee Lee’s third career major win at the Women’s PGA Championship, showcasing her dominance.'),
('mnop7890uvwx', 'Global Climate Summit 2025: Key Takeaways', 'A breakdown of the major agreements and debates from the 2025 Global Climate Summit held in Paris.'),
('qrst1234yzab', 'Caitlin Clark’s WNBA Commissioner’s Cup Final', 'Caitlin Clark leads the Indiana Fever to victory in a chippy game against the Sun, despite intense challenges.'),
('uvwx5678cdef', 'India’s Asian Para-Badminton Championship Triumph', 'Indian shuttlers win 27 medals, including four golds, in Thailand’s 2025 Asian Para-Badminton Championship.'),
('yzab9012ghij', 'Lionel Messi vs. PSG: Club World Cup 2025', 'Messi faces his former team PSG in a thrilling Club World Cup round of 16 match.'),
('cdef3456klmn', 'Aaron Rodgers on His NFL Journey and Marriage', 'Aaron Rodgers opens up about his decision to keep playing and his recent marriage in an exclusive interview.'),
('ghij7890opqr', 'US Open 2025: J.J. Spaun’s Dramatic Win', 'J.J. Spaun shares his emotions after clinching the 2025 US Open in a nail-biting finish.'),
('klmn1234stuv', 'Extreme Heat Disrupts MLB Games 2025', 'A look at how extreme heat affected players like Elly De La Cruz and Trent Thornton during MLB games.'),
('opqr5678wxyz', 'Malala’s Women’s Sports Investment Platform', 'CNN exclusive on Malala’s new initiative to boost women’s sports and promote equality.'),
('stuv9012abcd', 'Neeraj Chopra’s Paris Diamond League Throw', 'Neeraj Chopra’s stunning 88.16-meter javelin throw secures the Paris Diamond League 2025 title.'),
('wxyz3456efgh', 'Tyrese Haliburton’s NBA Finals Injury', 'An in-depth look at Tyrese Haliburton’s Achilles injury during Game 7 of the 2025 NBA Finals.'),
('abcd7890ijkl', 'Real Madrid’s Racial Abuse Controversy', 'Real Madrid manager discusses Antonio Rüdiger’s claims of racial abuse during the Club World Cup.'),
('efgh1234mnop', 'Coco Gauff’s French Open 2025 Triumph', 'Coco Gauff becomes the youngest American woman to win Roland Garros since Serena Williams.'),
('ijkl5678qrst', 'India’s Chess Olympiad Gold 2024', 'Indian men’s and women’s chess teams dominate the Budapest Chess Olympiad with gold medals.'),
('mnop9012uvwx', 'Chelsea’s Heat-Shortened Training Session', 'How extreme heat in Philadelphia impacted Chelsea’s Club World Cup preparations.'),
('qrst3456yzab', 'WNBA Franchise Value Soars in 2025', 'A study reveals WNBA franchises have increased in value by 180% since last year.'),
('uvwx7890cdef', 'Dodgers-Padres MLB Suspension Drama', 'MLB hands down suspensions after tensions escalate in the Dodgers-Padres series finale.'),
('yzab1234ghij', 'Oklahoma City Thunder’s NBA Title Run', 'A recap of the Thunder’s incredible journey to the 2025 NBA championship.'),
('cdef5678klmn', 'Koneru Humpy’s World Rapid Chess Title', 'Koneru Humpy claims her second women’s title at the 2025 World Rapid and Blitz Championship.'),
('ghij9012opqr', 'India’s Hockey Pro League Struggles', 'Analysis of India’s men’s and women’s hockey teams facing Belgium in the 2024-25 FIH Pro League.'),
('klmn3456stuv', 'New Delhi 2025 Para Athletics Championship', 'Delhi unveils logo and mascot for the first-ever World Para Athletics Championship in India.'),
('opqr7897wxyz', 'Aman Sehrawat’s Olympic Wrestling Bronze', 'Aman Sehrawat’s journey to a bronze medal in the men’s 57kg wrestling at Paris 2024.'),
('stuv1234abcd', 'Technological Doping in Sports Debate', 'Exploring the controversy around performance-enhancing equipment in sports like swimming.'),
('wxyz5678efgh', 'Saudi Arabia’s Soccer Disruption Plan', 'How Saudi Arabia is reshaping global soccer with massive investments.'),
('abcd9012ijkl', 'Milwaukee Brewers’ Record-Breaking Rookie', 'Jacob Misiorowski breaks a 125-year-old record with six perfect innings.'),
('efgh3456mnop', 'India’s Taiwan Athletics Open Dominance', 'India secures 12 gold medals at the Taiwan Athletics Open 2024, topping the medal tally.'),
('ijkl7890qrst', 'PR Sreejesh Named Junior Hockey Coach', 'Former Olympic hero PR Sreejesh takes on the role of India’s junior men’s hockey coach.'),
('mnop1234uvwx', 'Bihar to Host Women’s Kabaddi World Cup', 'Bihar prepares for the second Women’s Kabaddi World Cup in March 2025.'),
('qrst5678yzab', 'Pepe Reina’s Retirement Announcement', 'Spain and Liverpool legend Pepe Reina announces retirement at the end of the 2024-25 season.'),
('uvwx9012cdef', 'Enhanced Games: Doping Controversy', 'The Enhanced Games stirs debate as a doping-friendly sports event.'),
('yzab3456ghij', 'India’s Shooting World Cup 2025', 'India to host the ISSF Junior World Cup in the latter half of 2025.'),
('cdef7890klmn', 'Alcaraz’s Italian Open Victory 2025', 'Carlos Alcaraz defeats Jannik Sinner to claim his first Italian Open title.'),
('ghij1234opqr', 'Extreme Sports Fails Compilation', 'A collection of the most jaw-dropping fails in extreme sports from 2025.'),
('klmn5678stuv', 'Iran’s Missile Strike on US Air Base', 'Breaking news on Iran’s Operation Bashayer Al-Fath targeting Al-Udeid Air Base.'),
('opqr9012wxyz', 'Top 10 Cricket Moments of 2025', 'The best cricketing moments, including India’s Test series win against England.'),
('stuv3456abcd', 'Women’s Soccer World Cup 2025 Preview', 'A look ahead at the teams and players to watch in the 2025 Women’s Soccer World Cup.'),
('wxyz7890efgh', 'Global Economic Outlook 2025', 'Experts discuss the economic trends and challenges facing the world in 2025.'),
('abcd1234ijkl', 'NBA Top Plays of January 2025', 'The most exciting dunks, assists, and buzzer-beaters from the NBA this month.'),
('efgh5678mnop', 'Wimbledon 2025 Men’s Final Highlights', 'Carlos Alcaraz cements his Wimbledon favorite status with a thrilling final win.'),
('ijkl9012qrst', 'India’s Olympic Bid for 2036', 'India’s plan to host the 2036 Olympics, focusing on infrastructure and economic impact.'),
('mnop3456uvwx', 'Formula 1 2025 Season Preview', 'A preview of the drivers, teams, and tracks for the 2025 Formula 1 season.'),
('qrst7890yzab', 'US Election 2024 Recap', 'A detailed analysis of the 2024 US Presidential Election results and their impact.'),
('uvwx1234cdef', 'Best of NFL Week 1 2025', 'Highlights from the opening week of the 2025 NFL season, featuring top plays.'),
('yzab5678ghij', 'Tennis Trick Shots Compilation', 'The most creative and skillful trick shots from tennis players in 2025.'),
('cdef9012klmn', 'Middle East Tensions: 2025 Update', 'An overview of the geopolitical shifts in the Middle East as of June 2025.'),
('ghij3456opqr', 'Badminton World Championships 2025', 'Highlights from the 2025 Badminton World Championships, featuring top players.'),
('klmn7890stuv', 'Athletics World Records Broken in 2025', 'A compilation of new world records set in track and field events this year.'),
('opqr1234wxyz', 'Global Refugee Crisis 2025', 'An in-depth report on the ongoing refugee crisis and international responses.'),
('stuv5678abcd', 'Top 5 Boxing Knockouts of 2025', 'The most devastating knockouts from the boxing ring in 2025.'),
('wxyz9012efgh', 'India’s Asian Champions Trophy Win', 'India’s men’s hockey team defeats China to win the 2024 Asian Champions Trophy.'),
('abcd3456ijkl', 'WNBA 2025 Season Highlights', 'The best moments from the WNBA’s record-breaking 2025 season.'),
('efgh7890mnop', 'Climate Change Protests 2025', 'Footage and analysis of global climate protests in 2025, demanding action.'),
('ijkl1234qrst', 'MLB 2025 Home Run Derby', 'The biggest sluggers compete in the 2025 MLB Home Run Derby.'),
('mnop5678uvwx', 'UN General Assembly 2025 Highlights', 'Key speeches and decisions from the 2025 UN General Assembly.'),
('qrst9012yzab', 'Top 10 UFC Fights of 2025', 'The most thrilling UFC battles from the 2025 season.'),
('uvwx3456cdef', 'India’s Khelo India Youth Games 2024', 'Highlights from the 6th edition of Khelo India Youth Games held in January 2024.'),
('yzab7890ghij', 'Global AI Regulation Talks 2025', 'A discussion on international efforts to regulate artificial intelligence in 2025.'),
('cdef1234klmn', 'Cricket World Cup 2023 Best Moments', 'Relive the top moments from the 2023 Cricket World Cup, including India’s run.'),
('ghij5678opqr', 'Paris Olympics 2024 Wrestling Highlights', 'Key wrestling moments from the 2024 Paris Olympics, including Aman Sehrawat’s bronze.'),
('klmn9012stuv', 'Tech Innovations in Sports 2025', 'How new technology is transforming sports performance and fan experiences.'),
('opqr3456wxyz', 'India’s Test Cricket Victory 2025', 'England vs. India Test series highlights, with Root and Stokes leading the charge.'),
('stuv7890abcd', 'Global Health Crisis Update 2025', 'The latest on global health initiatives, including sickle cell disease screening.'),
('wxyz1234efgh', 'Golf’s US Open 2025 Top Shots', 'The best shots and moments from the 2025 US Open golf tournament.'),
('abcd5678ijkl', 'Women’s Cricket World Cup 2025 Preview', 'A look at the top teams and players for the 2025 Women’s Cricket World Cup.'),
('efgh9012mnop', 'Cybersecurity Threats in 2025', 'An analysis of the growing cybersecurity risks facing governments and businesses.'),
('ijkl3456qrst', 'NBA All-Star Game 2025 Highlights', 'The best dunks, shots, and moments from the 2025 NBA All-Star Game.'),
('mnop7890uvwx', 'India’s World Boxing Cup Final 2025', 'India hosts the prestigious World Boxing Cup Final in November 2025.'),
('qrst1234yzab', 'F1 Abu Dhabi Grand Prix 2025', 'Highlights from the thrilling 2025 F1 Abu Dhabi Grand Prix.'),
('uvwx5678cdef', 'Global Trade Wars 2025', 'An overview of the escalating trade tensions between major economies in 2025.'),
('yzab9012ghij', 'Top 10 Soccer Saves of 2025', 'The most incredible goalkeeper saves from the 2025 soccer season.'),
('cdef3456klmn', 'India’s Chess Grandmaster Milestones', 'Vidit Gujrathi and Vaishali Ramesh Babu shine at the Meier Grand Swiss.'),
('ghij7890opqr', 'Renewable Energy Advances 2025', 'Breakthroughs in renewable energy technologies shaping the future.'),
('klmn1234stuv', 'Rugby World Cup 2023 Best Tries', 'A compilation of the most spectacular tries from the 2023 Rugby World Cup.'),
('opqr5678wxyz', 'India’s Space Program 2025 Update', 'The latest achievements of ISRO and India’s space ambitions.'),
('stuv9012abcd', 'NHL Stanley Cup Finals 2025', 'Highlights from the 2025 NHL Stanley Cup Finals, featuring top teams.'),
('wxyz3456efgh', 'Global Food Security Crisis 2025', 'An in-depth look at the challenges facing global food security in 2025.'),
('abcd7890ijkl', 'Athletics Continental Tour 2024 Highlights', 'India’s dominance at the Taiwan Athletics Open with 16 medals.'),
('efgh1234mnop', 'Women’s Tennis Rising Stars 2025', 'Meet the new faces dominating women’s tennis in 2025.'),
('ijkl5678qrst', 'India’s Economic Vision 2047', 'Andhra Pradesh and Telangana launch ambitious economic plans for 2047.'),
('mnop9012uvwx', 'Top 5 Basketball Crossovers 2025', 'The slickest crossovers from the 2025 NBA and WNBA seasons.'),
('qrst3456yzab', 'Paris Paralympics 2024 Highlights', 'Nitesh K’s gold medal and other Indian successes at the 2024 Paralympics.'),
('uvwx7890cdef', 'Global Migration Trends 2025', 'How migration patterns are shaping global politics in 2025.'),
('yzab1234ghij', 'Cricket’s T20 World Cup 2024 Moments', 'The best moments from the 2024 T20 World Cup, featuring 20 teams.'),
('cdef5678klmn', 'AI in Sports: 2025 Innovations', 'How AI is revolutionizing sports analytics and training in 2025.'),
('ghij9012opqr', 'F1 Driver Rivalries 2025', 'The fiercest rivalries heating up the 2025 Formula 1 season.'),
('klmn3456stuv', 'Women’s Empowerment in Sports 2025', 'How women’s sports are gaining traction globally, with Malala’s initiative.'),
('opqr7890wxyz', 'Global Political Protests 2025', 'A look at major protest movements around the world in 2025.'),
('stuv1234abcd', 'Top 10 Olympic Moments 2024', 'The most unforgettable moments from the Paris 2024 Olympics.'),
('wxyz5678efgh', 'India’s Badminton Rising Stars', 'Young Indian shuttlers making waves in the 2025 season.'),
('abcd9012ijkl', 'Climate Action Plans 2025', 'How countries are implementing climate action strategies in 2025.'),
('efgh3456mnop', 'NFL Super Bowl 2025 Preview', 'A look at the teams and players to watch in the 2025 Super Bowl.'),
('ijkl7890qrst', 'India’s Sariska Tiger Reserve Update', 'Changes in the Critical Tiger Habitat boundaries in Rajasthan, 2025.'),
('mnop1234uvwx', 'Best of College Football 2025', 'The top plays and moments from the 2025 college football season.'),
('qrst5678yzab', 'Global Water Crisis 2025', 'An analysis of the growing water scarcity issues worldwide.'),
('uvwx9012cdef', 'Tennis Grand Slam Highlights 2025', 'The best moments from the 2025 Australian Open, French Open, and more.'),
('yzab3456ghij', 'India’s Khelo India Success Stories', 'How Khelo India is nurturing young talent in 2025.');
